package io.github.bzdgn.merdiven.statement.operation;

public enum OperationType {
	
	AND,
	OR,
	EQUALS,
	GREATER,
	GREATER_AND_EQUALS,
	SMALLER,
	SMALLER_AND_EQUALS,
	OPEN_PARENTHESIS,
	CLOSE_PARENTHESIS,
	OPEN_BRACKET,
	CLOSE_BRACKET,
	OPEN_ANGLE_BRACKET,
	CLOSE_ANGLE_BRACKET,
	OPEN_CURLY_BRACKET,
	CLOSE_CURLY_BRACKET,
	CUSTOM
	
}
